### ISSUE TITLE
Instruction for provisioning

### ISSUE THREAD

**Issue by Shm013** [hoptical/grafana-kafka-datasource#43]
**Is your feature request related to a problem? Please describe.**
It's no obvious how to add datasource using [provisioning](https://grafana.com/docs/grafana/latest/administration/provisioning/).

**Describe the solution you'd like**
Please add example how to add datasource in documentation.

Something like this:

```yaml
name:Kafka
type: hamedkarbasi93-kafka-datasource
jsonData:
  bootstrapServers: kafka1.example.com:9092,kafka2.example.com:9092
```

**Which sides should be considered to develop?**
- [ ] Frontend(React)
- [ ] Backend(Golang)
- [*] Documentation
