### ISSUE TITLE
[BUG] Plugin Unavailable 

### ISSUE THREAD

**Issue by daya-kulkarni** [hoptical/grafana-kafka-datasource#45]
**Describe the bug**
I am trying to use the backend plugin on version 9.3.4 and 9.4.2. In both cases I am getting an error that says that plugin in availble when i try to create and save the new datasource. I have installed the plugin two ways one one grafana version i have installed the folder way (manually) in the plugins dir and the other version via the grafana-cli command. Both show the datasource as an option but dont let me actually use it as I see the error below (in screenshot).

**To Reproduce**
1. Go to Setting 
2. Click on datasources 
3. Click on add new datasource button 
4. Search/filter for Kafka and click on datasource 
5. Add server (broker --> localhost:9092)
6. Click save and test
7. See error

**Expected behavior**
We should see the plugin be available and say datasouce added (green message)

**Screenshots**
![image](https://user-images.githubusercontent.com/38143515/224856024-5358c006-b5fa-4d10-a187-3a7584a338df.png)
**Desktop Information:**
 - OS: Ubuntu 20.04
 - Browser: chrome
 - Plugin Version: 0.2.0
 - Grafana Version: 9.4.2 && 9.3.4

**Addtional Context**
Do I need certain permissions that the server runs at?

**Comment by ustbly** [comment]
I use Grafana that version is 9.4.3,the same error also appears,that sucks!

**Comment by jessechencx** [comment]
Anyone have resolved the problem?

**Comment by tanis2000** [comment]
I found out what the issue is. At least in my case. It looks like the Grafana docker image is built for arm64 (I am running it on an Apple Silicon chip) but the plugin is only amd64, which means that it will fail badly.

One workaround is to force the Grafana instance to run with the amd64 image. It will be slower but it will work.

My compose file looks like the following:

```yaml
version: '2'
services:
  grafana:
    image: 'grafana/grafana-oss:latest'
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=hamedkarbasi93-kafka-datasource
    platform: 'linux/amd64'
```
